### ISSUE TITLE
[Bug Report]: Offhand item usage

### ISSUE THREAD

**Issue by fucksophie** [Crazy-Crew/CrazyVouchers#31]
### Server Version

1.19.4

### Server Platform

Paper

### Describe the bug

You can't use vouchers in your offhand - the code doesn't allow for a permission to exist for offhand usage

### Steps to reproduce

1. Hold a voucher in your offhand
2. Rightclick.

### Additional context

https://github.com/Crazy-Crew/CrazyVouchers/blob/1b0192939759912e8ef513501e65592a8395d733/src/main/java/com/badbones69/crazyvouchers/controllers/VoucherClick.java#L57
The permission message is sent, even though no permission is checked.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
I don't even remember fixing this.

**Comment by ryderbelserion** [comment]
I just realized, there is no permission check because there doesn't need to be one. it isn't actually a bug.

we check if the hand is not null and if the the slot is off_hand thus the message is called no_permission_to_use_voucher_in_offhand because technically you don't. the message is configurable so you can set it to anything you want regardless of what the key is called in the config.yml

**Comment by fucksophie** [comment]
The main issue is the fact that there is no way to use the vouchers while it's in your offhand.

**Comment by ryderbelserion** [comment]
The proper thing to do then is make a suggestion, a bug is unintended. this is intended.
